### ISSUE TITLE
How to provide header information

### ISSUE THREAD

**Issue by michaelboke** [savaki/swag#1]
First of all, what a nice clean way to generate a swagger spec file in code.

I was just looking at it and wondered how do you specify the Header information for the response object?

**Comment by savaki** [comment]
Good point.  I suppose I've never specified something in the header before.  I'll go ahead and add that.  Thanks.

**Comment by savaki** [comment]
swag ```endpoint.Response``` now supports a ```endpoint.Header``` option

```go
e := endpoint.New("get", "/", "get thing",
  endpoint.Response(http.StatusOK, Model{}, "successful",
    endpoint.Header("X-Rate-Limit", "integer", "int32", "calls per hour allowed by the user"),
  ),
)
```
